---
# ansible-galaxy collection install -r requirements.yml
# pip install -r ~/.ansible/collections/ansible_collections/community/vmware/requirements.txt
collections:
  - name: community.vmware
  - name: community.sops
