esxi_password: ENC[AES256_GCM,data:15iM1rfuWz7JbA==,iv:kW5sFK+AabPJJjgiD2SVZtztICOsyh2etxh4XxfdTDE=,tag:tLbOqncJaspDxVIoIzRGtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age164vhfzer4edwf66a38ag0vrh74hrxqjrzgajq83ctnn929mr752s0cddv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3allqUW5YWUZOYndOVEZP
            REYzaUplMmhzenEvZTJZVUMyNFBNOGpCZ1ZrCkx1YWs3TmpybHRuYU9QWE1PTFpo
            RllkcUIycXA1bUVGeVlQSDZINngxZTAKLS0tIDhjSmtsRWxseHI2UFNZVmxmUGlw
            MmJWb2Q4T2FsZ1ZVN1RDTkk1SG9kTG8KGdmnOKI2LXJRDoEoWyLpIOdRJ5E3plQ1
            /AUdDO8OVz7jDb/CmPz9rSDVkRVxnrHawLGTkjKJ1tW6mM+fncv9Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T04:53:45Z"
    mac: ENC[AES256_GCM,data:OmNg88Eyr3SsQHsMsmdj57bYtr+k+uDsO3vzZhSESiEOFdk8XB406V6Oy62PlmwPIi3gmZ989KCWhVIJBuKzg47wnKyEVn6t7qqkZsLLma6qpQjVXJx4mIYXi6qMOasc4Y9CiZBgUlRMJrH9bC0v8PX0axfvCEAwEC/Alp1FaGM=,iv:QwEDmHgRT5Run4aeJfpGHzqMzRqeMxEk+VCyROOZPgE=,tag:ZKIPkDiJKn4B0xakqfBkJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
