---
- name: Standalone ESXI playbook
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    - ansible_python_interpreter: /usr/local/bin/python3

  vars_files:
    - vars/esxi_vars.yml

  tasks:
    - name: Load SOPS Secrets and Include variables
      community.sops.load_vars:
        file: esxi.sops.yml
      environment:
        SOPS_AGE_KEY_FILE: '~/sops-key.txt'

    - name: Make sure requirements are met to run vmware modules
      become: yes
      pip:
        name: PyVmomi
        state: present

    - name: Set NTP servers for all ESXi Host in given Cluster
      community.vmware.vmware_host_ntp:
        hostname: '{{ esxi_hostname }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: False
        state: present
        ntp_servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org

    - name: Start ntpd setting for an ESXi Host with Service policy
      community.vmware.vmware_host_service_manager:
        hostname: '{{ esxi_hostname }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        esxi_hostname: '{{ esxi_hostname }}'
        service_name: ntpd
        service_policy: on
        validate_certs: False
        state: present

    - name: Manage multiple settings for an ESXi host
      community.vmware.vmware_host_config_manager:
        hostname: '{{ esxi_hostname }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        esxi_hostname: '{{ esxi_hostname }}'
        validate_certs: False
        options:
          'Config.HostAgent.log.level': 'verbose'
          'Annotations.WelcomeMessage': 'Hello World'

    - name: Automatically answer if a question locked a virtual machine
      block:
        - name: Power on a virtual machine without the answer param
          vmware_guest_powerstate:
            hostname: "{{ esxi_hostname }}"
            username: "{{ esxi_username }}"
            password: "{{ esxi_password }}"
            validate_certs: false
            folder: "{{ datastore1_folder }}"
            name: "{{ item }}"
            state: powered-on
          loop: "{{ vm_cluster }}"

      rescue:
        - name: Power on a virtual machine with the answer param
          vmware_guest_powerstate:
            hostname: "{{ esxi_hostname }}"
            username: "{{ esxi_username }}"
            password: "{{ esxi_password }}"
            validate_certs: false
            folder: "{{ datastore1_folder }}"
            name: "{{ item }}"
            answer:
              - question: "msg.uuid.altered"
                response: "button.uuid.copiedTheVM"
            state: powered-on
          loop: "{{ vm_cluster }}"
